site_name: CMSTkModLab
site_url: http://desy-fh-elab.github.io/cmstkmodlab
site_description: Documentation for DESY CMS Lab Software
site_author: Andreas Mussgiller

repo_url: https://github.com/DESY-FH-ELab/cmstkmodlab

nav:
- Home: index.md
- Build:
    - configure: build/configure.md
    - Ubuntu Linux: build/UbuntuLinux.md
    - Raspbian Linux: build/RaspbianLinux.md
    - OSX El Capitan: build/OSXElCapitan.md
- Thermo:
    - thermoDAQ: thermo/thermoDAQ.md
    - thermoDAQ2: thermo/thermoDAQ2.md
- Defo:
    - defoDAQ: defo/defoDAQ.md
    - defoDAQ Scripting: defo/defoDAQScripting.md
- Assembly: assembly/index.md
- Plasma Cleaner: plasma/index.md
- Pump Station:
    - usage: pumpstation/index.md
    - setup: pumpstation/setup.md
- License: license.md

theme: readthedocs
